cloudposse/terraform-aws-elastic-beanstalk-environment

.gitignore, main.tf, variables.tf
* Added `solution_stack_name` attribute to `aws_elastic_beanstalk_environment` and to `variables.tf`
* Format code (`terraform fmt`)
* We need the ability to specify the solution stack to base the environment off of (e.g. Docker, Tomcat, Java, Node, Python, Go, Ruby, IIS)
* For example: `"64bit Amazon Linux 2015.09 v2.0.4 running Go 1.7"`
* Elastic Beanstalk will pre-install the specified stack during the environment creation
* https://www.terraform.io/docs/providers/aws/r/elastic_beanstalk_environment.html#solution_stack_name
* https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/concepts.platforms.html#concepts.platforms.nodejs
=> Add `solution_stack_name` attribute to `aws_elastic_beanstalk_environment`

main.tf, variables.tf
* Remove `template_name`
* Even if it's empty, it conflicts with `solution_stack_name`
* Terraform does not like `template_name` and `solution_stack_name` to be provided at the same time
=> Remove `template_name`

main.tf, variables.tf
* Assign `attributes` and `tags` from `variables.tf` to internal `label` module
* The internal `label` module's `attributes` and `tags` should be visible from outside of the top-level module
* If `attributes` and `tags` are not accessible from outside, sometimes it's impossible to create more than one AWS resource from the top-level module
* Without additional `attributes`, it's not possible at all to create `aws_security_group` inside the module since many security groups with the same name `${module.label.id}` are created in the same solution
=> Assign `attributes` and `tags` from `variables.tf` to `label` module

.gitignore, main.tf, variables.tf
* Add custom (application specific) `ENV` variables to the `EB` container
* For many applications (_e.g._ `Jenkings` or `WordPress`) we need to provide custom `ENV` variables into the `EB` container, _e.g._ `EFS` host, `Jenkins` initial user and password, or database user and password
* `README.md`
* Describe two ways of providing application `ENV` variables to the `EB` container:
* Using variable `config_source`
* Using variable `env_map`
=> Add Support for Environment Variables Passed by Map

main.tf
* Fix element() for empty list workaround
* Fix key-value association
* For empty env_vars there was error `element()` may not be used with an empty list in:
https://github.com/hashicorp/terraform/issues/9858
* `keys()` return list sorted in lexical order, but `values()` in order as defined in map.
So to make key-value association we need to use `lookup()`
=> Support Empty Env List and Return Stable Values

main.tf, variables.tf
* Added `Application Load Balancer` health check settings in namespace `aws:elasticbeanstalk:environment:process:default`
* The `ALB` health check does not take into account the `Elastic Beanstalk` health check path
* http://docs.aws.amazon.com/elasticbeanstalk/latest/dg/environments-cfg-applicationloadbalancer.html
* http://docs.aws.amazon.com/elasticbeanstalk/latest/dg/environments-cfg-applicationloadbalancer.html#alb-default-process.config
* http://docs.aws.amazon.com/elasticbeanstalk/latest/dg/command-options-general.html#command-options-general-elasticbeanstalkapplication
=> Add `Application Load Balancer` health check settings

main.tf
* Changed the way the custom ENV vars are calculated in `aws:elasticbeanstalk:application:environment` setting 
* Using `null_resource` to generate key/value pairs for ENV vars like this:
```
resource "null_resource" "env_vars" {
count = 50
triggers {
key = "${count.index < length(var.env_vars) ?
element(concat(keys(var.env_vars),list("")), count.index) :
format(var.env_default_key, count.index+1)
}"
value = "${count.index < length(var.env_vars) ?
lookup(var.env_vars, element(concat(keys(var.env_vars),list("")), count.index), var.env_default_value) :
var.env_default_value
}"
}
}
setting {
namespace = "aws:elasticbeanstalk:application:environment"
name      = "${null_resource.env_vars.0.triggers.key}"
value     = "${null_resource.env_vars.0.triggers.value}"
}
setting {
namespace = …
```
=> Change custom ENV vars key/value calculation

main.tf
* Add `AmazonEC2ContainerRegistryReadOnly` managed policy to `EB`
* To provide read-only access to all Amazon ECR repositories in the account
* When `CodePipeline` builds and pushes `Docker` images to `ECR` and then deploys the file `Dockerrun.aws.json` to `EB` with the `ECR` repo URL specified, `EB` needs permissions to pull the `Docker` image from the ECR repo to deploy it to `EC2` instances
* http://docs.aws.amazon.com/elasticbeanstalk/latest/dg/create_deploy_docker.container.console.html
* http://docs.aws.amazon.com/AmazonECR/latest/userguide/ecr_managed_policies.html#AmazonEC2ContainerRegistryReadOnly
=> Add `AmazonEC2ContainerRegistryReadOnly` policy to provide read-only access to `ECR` repositories

main.tf, outputs.tf
* Added `ec2_instance_profile_role_name` to outputs
* To be able to attach additional `aws_iam_role_policy_attachment`'s to the instance profile role from other modules
=> Add `ec2_instance_profile_role_name` to outputs

README.md, main.tf, variables.tf
* Add variable for `tier`
* Currently, your module for elastic beanstalk environment doesn't have a way to set the tier for the application to be "Worker" because it is hardcoded to "WebServer".  I am asking that a variable is created for the tier with it defaulting to "WebServer" so it disrupts as little as possible. I will put in a PR shortly this Issue number.
* This is the PR for Issue #21
=> Add variable for environment tier

main.tf
* Bump `terraform-null-label` version to `0.3.1`
* Latest version with bug fixes
=> Bump `terraform-null-label` version to `0.3.1`

main.tf
* Removed the ingress rule from EC2 Security Group
```hcl
ingress {
from_port   = 0
to_port     = 0
protocol    = -1
cidr_blocks = ["0.0.0.0/0"]
}
```
* Bad security practice
* Too broad access from any IP address by default
* Access should be controlled by provided Security Groups instead of IP ranges
* Was overriding the next ingress rule for the same Security Group
```hcl
ingress {
from_port       = 0
to_port         = 0
protocol        = -1
security_groups = ["${var.security_groups}"]
}
```
=> Fix Security Group ingress rules

main.tf
`current` option for aws provider generate the following deprecation warning:
```
$ terraform plan
Warning: module.aws-elastic-beanstalk-environment.data.aws_region.default: "current": [DEPRECATED] Defaults to current provider region if no other filtering is enabled
[...]
```
Source: https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#190-february-09-2018
Thanks for this module !
=> Remove unnecessary current option for aws provider

README.md, main.tf, variables.tf
* This pull request just adds a variable to enable the automatic creation of Elastic IP attached to instances.
* If there is not NAT gateway in `private_subnets` (but an Internet gateway) there is a need to attach Elastic IP to instances in order to communicate with Elastic BeanStalk publics endpoints.
* I agree with the default value set before, `false`; a correct setup has a *NAT gateway* in a *private* subnet :)
* https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/vpc.html
* https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/vpc-no-nat.html
=> Use a variable to enable aws:ec2:vpc:AssociatePublicIpAddress

README.md, main.tf, variables.tf
Add a setting to use `Immutable` strategy of deployment (instead changing instances in-place, create new ones)
Because immutable strategy ensure that all the process of deployment can be done from scratch (don't depend on old components, force creation of new resources for changes).
There is another `aws:elasticbeanstalk:command:DeploymentPolicy`, `AllAtOnce`, but it disables rolling deployments and always deploy to all instances simultaneously.
No sure if it is wanted to create a variable for this case (?)
https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/using-features.rollingupdates.html
https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/environmentmgmt-updates-immutable.html
https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/using-features.rolling-version-deploy.html
=> Set variable for rolling update policy

README.md, main.tf, variables.tf
This add a variable to lock down ssh on EC2 instances
Because even if a keypair is required to authenticate, bruteforce can happen on the instance (more often if an Elastic IP is attached). This can be used to authorize only a bastion host to connect. The default to let access opened is the same as AWS BeanStalk.
https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/command-options-general.html
=> Add variable for SSHSourceRestriction

README.md, main.tf, variables.tf
Set a variable for changing default EBS. Please note that because we specify the `setting`, default values come from this module, not from Elastic BeanStalk (which can be platform specific).
Because `8G` might be very small is there is lot of logs generated.
https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/command-options-general.html
=> Add variable for EBS type and size

README.md, main.tf, variables.tf
Add variables for maintenance window, update level and instance refresh.
For production, a desired value for update_level can be `patch` while the default `minor` can be for staging envs.
There is no need to set a variable for `ManagedActionsEnabled` because if set to false will produce configuration error because , `PreferredStartTime` and `UpdateLevel` are set.
* https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/command-options-general.html#command-options-general-elasticbeanstalkmanagedactionsplatformupdate
* https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/command-options-general.html#command-options-general-elasticbeanstalkmanagedactions
=> Add variables for managed updates

README.md, main.tf, variables.tf
Change the default Availability Zones from `Any 2` to  `Any`.
If there is more than 2 AZs in a region, use all AZs:
`Availability Zones (AZs) are distinct locations within a region that are engineered to be isolated from failures in other AZs and provide inexpensive, low-latency network connectivity to other AZs in the same region. Choose the number of AZs for your instances.`
For example region **eu-west-1** and **eu-west-3** has 3 differents AZs.
~~I think there is no need to provide a variable for this; it works on all cases (1 instance, 3 instances, 6 instances, etc...).~~
* https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/command-options-general.html
* https://github.com/jsonmaur/aws-regions (unofficial list of all AZs per regions)
=> Add a variable for Availability Zones

README.md, main.tf, variables.tf
:warning: ~~Please don't merge directly, this break the creation of the environment if default not defined!~~ :warning:
Enable some interesting CloudWatch metrics. I think this is considered as custom metrics (so charges can apply) because they are not created by default.
Without that, it is difficult to get metrics from the ELB or instances *directly*.
Some metrics about instances such as `RootFilesystemUtil` are custom metrics but not managed by user!
~~the option need to be defined with a value, or not defined (so empty default produce an error)~~:
```
Failed Environment update activity. Reason: Configuration validation exception: Invalid option specification (Namespace: 'aws:elasticbeanstalk:healthreporting:system', OptionName: 'ConfigDocument'): Unknown configuration setting.
```
~~I …
=> Add custom metrics for CloudWatch

README.md, docs/terraform.md, main.tf, variables.tf
* Bump `terraform-null-label` version
* Make `zone_id` optional
* New `terraform-null-label` version fixes the issue with empty tag values (which breaks Elastic Beanstalk environment)
* Don't create a DNS record if `zone_id` is empty. Not all applications require a friendly DNS name for EB environment
=> Bump `terraform-null-label` version. Make `zone_id` optional

README.md, docs/terraform.md, main.tf, variables.tf
Add the possibility to use existing security groups when creating load balancer, and stop the creation of the default security group.
The default behaviour when creating a load balancer is to create a security group which allow `0.0.0.0` to access to it. I need to allow only a specific cidr.
There are two variables :
* loadbalancer_security_groups : list of security groups to attach
* loadbalancer_managed_security_group : A single SG. If you don't fill this variable, it will continue to create a default security group.
Example : Use a custom SG which allow only my network :
```
loadbalancer_security_groups = ["${module.sg.this_security_group_id}"]
loadbalancer_managed_security_group = "${module.sg.this_security_group_id}"
```
If you don't fill theses two variables, you have the classical …
=> Add Load balancer security groups

README.md, docs/terraform.md, main.tf, variables.tf
Add `orce_destroy` option for S3 bucket
After running destroy the S3 bucket for load balancer logs is not destroyed
=> Add force_destroy option for S3 bucket

main.tf
The `terraform-null-label` grew a bit complex and is throwing errors when used:
```
* module.sc-api-env-active.module.elastic_beanstalk_environment.module.label.data.null_data_source.tags_as_list_of_maps: data.null_data_source.tags_as_list_of_maps: value of 'count' cannot be computed
```
Changed the label to use `terraform-terraform-label` instead.
tf plan `example/complete` and verify it finishes successfully.
=> Use terraform-terraform-label 0.1.6 for module.label

README.md, docs/terraform.md, main.tf, variables.tf
Support log settings.
- Added support for `aws:elasticbeanstalk:hostmanager`, `aws:elasticbeanstalk:cloudwatch:logs`, and `aws:elasticbeanstalk:cloudwatch:logs:health` options
https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/environments-cfg-logging.html
- Tested locally with a parent module worked as expected
=> DEVOPS-232: Add aws:elasticbeanstalk:cloudwatch:logs support

README.md, docs/terraform.md, main.tf, variables.tf
There are two types of beanstalk, LoadBalanced and SingleInstance.  Not entirely sure if the SingleInstance type is ever a great choice, but I use it sometimes for when I want the ElasticBeanstalk infrastructure sugar without the horizontal scaling, e.g. right now for running a slackbot
=> Add option to specify environment type

README.md, README.yaml, docs/terraform.md, main.tf, variables.tf
Have tested with load balanced environment, but not SingleInstance.
Terraform wants to update the settings on the environment every time, even with no changes (and even using the module from `master`), is this normal?
=> Allow setting elb_scheme for choosing internal or public LB

main.tf
Fixes https://github.com/cloudposse/terraform-aws-elastic-beanstalk-environment/issues/79
=> Add AWSElasticBeanstalkMulticontainerDocker role for ec2 instance profile

README.md, docs/terraform.md, examples/complete/fixtures.us-east-2.tfvars, examples/complete/main.tf, examples/complete/variables.tf, main.tf, variables.tf
* Add `env_vars` variable
* Make it easier for the clients to provide ENV vars (as a map of key/value pairs) to the applications running on Elastic Beanstalk instead of providing ENV vars in the more complicated `setting` block
=> Add `env_vars` variable

main.tf
* Remove `Namespace` from Elastic Beanstalk environment tags
* `Namespace` should be removed as well as `Name` from the tags since any string that contains `Name` forces recreation
* Probably because of https://blog.codinghorror.com/regular-expressions-now-you-have-two-problems/
=> Remove `Namespace` from Elastic Beanstalk environment tags

README.md, docs/terraform.md, main.tf, variables.tf
`dns_subdomain` allows a more customized name than the default `name` provided so consumers can scope their subdomains by environment or other custom needs.
=> Adds `dns_subdomain` var to control final hostname

.github/workflows/slash-command-dispatch.yml, README.yaml
* secret name updated
* github doesn't allow to use secrets with `GUTHUB_` prefix
=> triage the README update script from fork

test/src/examples_complete_test.go
* unique attribute added to tests
* to avoid tests fails due to S3 bucket already exists
=> unique attribute added

README.md, docs/terraform.md, main.tf, variables.tf
* Allow usage of spot instances in beanstalk environments
* We want to use spot instances in some of our beanstalk environments and this was missing in the module
* `closes #100`
=> Add support for spot instances

main.tf
* Fix of #43 for terraform 0.12.x for now and separated classic & application ELB settings 
* As #43 shows, terraform 0.12.x shows settings changes during ```terraform plan```when no changes were done.
* furthermore, if you are using an application load balancer the classic ELB settings are always shown as changes. I used the AWS documentation of "deprecated" classic ELB values if you are using an ALB to decide which settings go into which of the two lists. 
* closes #43 for terraform 0.12.x
=> Settings changes fix

README.md, docs/terraform.md, main.tf, variables.tf
* Added support for specifying `ami_id`
* `ami_id` is a key configurable option in EB environments
* https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/AMIs.html
=> feat: add support for ami_id

main.tf
* spot instance variables and dynamic variables where not covered
* sorting for securitygroups was not enough
those two issues resulted in still having terraform plan showing changes
even if no changes were present.
* added resource fix needed for terraform 0.12.x  that is needed due to https://github.com/hashicorp/terraform/issues/22563#issuecomment-548790058
* Fixes left over issues in https://github.com/cloudposse/terraform-aws-elastic-beanstalk-environment/pull/114 introduced with parallel changes for SpotOn configuration and missing a sort
=> Terraform 0.12 setting fix

main.tf
* Do not get data and do not create s3 bucket for elb logs in case of an environment isn't LoadBalanced type
* I use SingleInstance env type and I don't need the s3 bucket for lb logs
=> LB resources only for LoadBalanced env type

main.tf
* Four settings relating to EC2 Spot prices (added in #115) were missing an empty `resource` attribute.  This causes `terraform apply` to constantly reapply the configuration, even if no code or Beanstalk config has changed.
* As #43 shows, terraform 0.12.x shows settings changes during `terraform plan` when no changes were done.
* Broken by #115.
* Applies to #43.
=> Add missing resource attributes to Spot.

README.md, docs/terraform.md, examples/complete/main.tf, examples/complete/versions.tf, main.tf, variables.tf
Adds two variables `extended_ec2_policy_document` and `prefer_legacy_ssm_policy` to be able to control IAM policies attached to EC2 instance roles.
As noted in #75, currently EC2 instances are configured with a role that gives full S3 access. This is undesirable for security reasons.
* `AmazonEC2RoleforSSM` is a managed policy allowing to use SSM features (Session Manager, for example) with EC2 instances and it gives full S3 access.
* There is an inline policy containing a statement with SID `AllowS3OperationsOnElasticBeanstalkBuckets` that also grants full S3 access.
The `prefer_legacy_ssm_policy` variable (when set to `false`) will replace `AmazonEC2RoleforSSM` with `AmazonSSMManagedInstanceCore` which is recommended by AWS: https://docs.aws.amazon.com/systems-manager/latest/userguide/se …
=> Allow to restrict S3 access

README.md, docs/terraform.md, examples/complete/main.tf, main.tf, variables.tf
* `mfa_delete` removed
* Bridgecrew check `Ensure S3 bucket has MFA delete enabled` skipped
* Because terraform doesn't support this argument to be toggled (https://github.com/hashicorp/terraform-provider-aws/issues/629).
* To satisfy Bridgecrew compliance scan
* https://github.com/hashicorp/terraform-provider-aws/issues/629
=> mfa_delete removed

.github/workflows/auto-context.yml, README.md, context.tf, docs/terraform.md, examples/complete/context.tf, examples/complete/main.tf, examples/complete/versions.tf, main.tf, versions.tf
- update context.tf to v0.23.0 
- minimum required Terraform version bumped to 0.13.0 
- readme updated, Bridgecrew compliance badges added
- It allows for setting the letter case of tag names and labels
- we have dropped support for Terraform 0.12
- To be able see and fix the recommendations from Bridgecrew so we can position our modules as standards compliant
=> minimum required Terraform version bumped to 0.13.0, context.tf updated, readme updated

README.md, README.yaml, docs/terraform.md, examples/complete/main.tf, main.tf, variables.tf
Adds a new variable `prefer_legacy_ssm_policy` to be able to control IAM policy attached to the service role.
As mentioned in #171 , the `AWSElasticBeanstalkService` policy is getting deprecated and AWS recommends to replace it with `AWSElasticBeanstalkManagedUpdatesCustomerRolePolicy`. Since existing environments may still rely on permissions existing in the deprecated policy, the `prefer_legacy_ssm_policy` variable's default value is set to `true` for backward compatibility.
Closes #171
=> Update service role policy

.github/renovate.json, .github/workflows/auto-context.yml, .github/workflows/auto-format.yml, .github/workflows/auto-readme.yml, .github/workflows/chatops.yml, .github/workflows/validate-codeowners.yml, Makefile
Change all references to `git.io/build-harness` into `cloudposse.tools/build-harness`, since `git.io` redirects will stop working on April 29th, 2022.
- DEV-143
=> git.io->cloudposse.tools update

main.tf, outputs.tf
This fixes the issue with the output of the ALB bucket name, it also incorporates the option to manually set the bucket name to make it backward compatible with the previous deployment (what already has the bucket name assigned)
Because it is a bug that is on production code as commented on [here](https://github.com/cloudposse/terraform-aws-elastic-beanstalk-environment/commit/92c3ba4e23e87653fe53357399901d65881dbb98#diff-de6c47c2496bd028a84d55ab12d8a4f90174ebfb6544b8b5c7b07a7ee4f27ec7R87)
=> Bugfix issue with ALB bucket output name and name in general

main.tf
Include fix for https://github.com/cloudposse/terraform-aws-lb-s3-bucket/issues/81
Bumped elb_logs module version from 0.19.0. to 0.20.0
To include a bugfix in order to fix #259.
The actual fix is in this commit: https://github.com/cloudposse/terraform-aws-lb-s3-bucket/commit/a642b8743328c5ef2e9a89ed81f63f26e30501a8#diff-dc46acf24afd63ef8c556b77c126ccc6e578bc87e3aa09a931f33d9bf2532fbb
- relates to https://github.com/cloudposse/terraform-aws-lb-s3-bucket/issues/81 
- closes #259
=> Bump elb_logs module version to fix #259
